### ISSUE TITLE
Filter posts using child uid

### ISSUE THREAD

**Issue by DushyantMainwal** [firebase/FirebaseUI-Android#789]
I have a firebase structure like this:

```
posts:
 pushKey1:
    text: "text1"
    uid: "userID1"
 pushKey2:
    text: "text2"
    uid: "userID2"

users:
   userID3:
      following:
             userID1:true
```

Here, I only want to show the posts for the uid which are followed by userID3(i.e. userID1).

```
DatabasReference keyRef = databaseReference.child("users") .child(firebaseUser.getUid()).child("following");
        firebaseRecyclerAdapter = new FirebaseIndexRecyclerAdapter<PostsModel, PostViewHolder>(
                PostsModel.class,
                R.layout.posts_listitems,
                PostViewHolder.class,
                keyRef,
                databaseReference.child("posts").orderByChild("uid").equalTo(true)
        ) {

            @Override
            protected void populateViewHolder(final PostViewHolder viewHolder, PostsModel model, final int position) {
                viewHolder.ques_text.setText(model.getQues_text());
};

```

This is my Java Code but it doesn't show any posts.
Is there a way to reference the child node **uid** in posts?
